a = input("Enter your name:")
print("my name is",a)
x = (input("Enter first no.:"))
y = (input("Enter second no.:"))
print(x + y)
print(int(x) + int(y))
x = int(input("Enter first no.:"))
y = int(input("Enter second no.:"))
print(x + y)